# Generated by Django 4.2.1 on 2023-07-06 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_ID', models.CharField(max_length=15, unique=True)),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('car owner', 'Car owner'), ('car renter', 'Car renter')], default='car renter', max_length=10)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('AdminName', models.CharField(max_length=50)),
                ('AdminPhonenum', models.CharField(max_length=12)),
                ('AdminEmail', models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CarOwner',
            fields=[
                ('OwnID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('OwnName', models.CharField(max_length=50)),
                ('OwnPhonenum', models.CharField(max_length=12)),
                ('OwnEmail', models.EmailField(max_length=255)),
                ('OwnGender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='CarRenter',
            fields=[
                ('RentID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('RentName', models.CharField(max_length=50)),
                ('RentPhonenum', models.CharField(max_length=12)),
                ('RentEmail', models.EmailField(max_length=255)),
                ('RentGender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('RentLicense', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('FeedID', models.AutoField(primary_key=True, serialize=False)),
                ('Comment', models.TextField(max_length=255)),
                ('RentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.carrenter')),
            ],
        ),
        migrations.CreateModel(
            name='CarDetail',
            fields=[
                ('CarPlatenum', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('CarImg', models.ImageField(upload_to='images/car')),
                ('CarModel', models.CharField(max_length=50)),
                ('NumofPassenger', models.PositiveIntegerField()),
                ('CarPrice', models.PositiveIntegerField()),
                ('OwnID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.carowner')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('BookID', models.AutoField(primary_key=True, serialize=False)),
                ('BookDate', models.DateField()),
                ('ReturnDate', models.DateField()),
                ('TotalPrice', models.PositiveIntegerField()),
                ('CarPlatenum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.cardetail')),
                ('RentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.carrenter')),
            ],
        ),
    ]
